"""
stacking_model.py
=================
Production-grade Stacked Ensemble for Carbon Biomass Estimation.

Architecture
------------
Level 0 (Base Learners) : RandomForest | XGBoost | SVR
Level 1 (Meta-Learner)  : Ridge Regression

The meta-model is trained exclusively on Out-of-Fold (OOF) predictions
generated by the base learners, preventing target leakage and ensuring
the final model generalises to unseen environments.

Author : <Your Name>
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional, Tuple

import joblib
import numpy as np
import pandas as pd
from sklearn.base import clone
from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import GridSearchCV, KFold, train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from xgboost import XGBRegressor


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

RAW_FEATURES: List[str] = [
    "clay",
    "sand",
    "silt",
    "elev",
    "annual_precip",
    "peat_frac",
    "Hydraulic_Stress",
    "NDVI",
]

DERIVED_FEATURES: List[str] = ["precip_clay_interaction"]

MODEL_FEATURES: List[str] = RAW_FEATURES + DERIVED_FEATURES

TARGET: str = "AGB"

BASE_MODEL_NAMES: List[str] = ["RF", "XGB", "SVR"]


# ---------------------------------------------------------------------------
# Data Layer
# ---------------------------------------------------------------------------


class BiomassDataHandler:
    """
    Handles data ingestion, feature engineering, imputation, and scaling.

    All preprocessing artefacts (imputer, scaler) are fitted on the training
    partition only and persisted so the same transforms can be applied at
    inference time without re-fitting.

    Parameters
    ----------
    file_path : str
        Absolute path to the CSV containing the labelled dataset.
    features : list[str]
        Ordered list of feature column names used during model training.
    target : str
        Name of the response / target column.
    """

    def __init__(self, file_path: str, features: List[str], target: str) -> None:
        self.file_path = file_path
        self.features = features
        self.target = target
        self.imputer = SimpleImputer(strategy="mean")
        self.scaler = StandardScaler()
        self.df: Optional[pd.DataFrame] = None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def load(self) -> pd.DataFrame:
        """Load CSV from *file_path* and cache in ``self.df``."""
        if not os.path.exists(self.file_path):
            raise FileNotFoundError(f"Dataset not found at: {self.file_path}")

        self.df = pd.read_csv(self.file_path)
        print(f"[BiomassDataHandler] Loaded {len(self.df):,} records.")
        return self.df

    def engineer_features(self) -> None:
        """
        Create derived interaction features from raw covariates.

        Adds the following columns in-place:
        - ``precip_clay_interaction`` : annual_precip × clay
        """
        if self.df is None:
            raise RuntimeError("Call .load() before engineering features.")

        self.df["precip_clay_interaction"] = (
            self.df["annual_precip"] * self.df["clay"]
        )
        print("[BiomassDataHandler] Feature engineering complete.")

    def get_full_data(self) -> Tuple[pd.DataFrame, pd.Series]:
        """Return raw (un-scaled) X and y for the full dataset."""
        if self.df is None:
            self.load()
        return self.df[self.features].copy(), self.df[self.target].copy()

    def prepare_split(
        self,
        X_train_raw: Optional[pd.DataFrame] = None,
        X_test_raw: Optional[pd.DataFrame] = None,
        test_size: float = 0.2,
    ) -> Tuple[np.ndarray, np.ndarray, pd.Series, pd.Series]:
        """
        Impute and scale feature matrices, fitting transforms on the training
        partition exclusively.

        Parameters
        ----------
        X_train_raw, X_test_raw : optional DataFrames
            If provided, these are preprocessed directly (for nested CV use).
            If omitted, a fresh random split is performed.
        test_size : float
            Fraction of the dataset reserved for testing (default 0.20).

        Returns
        -------
        X_train_sc, X_test_sc : np.ndarray
        y_train, y_test : pd.Series
        """
        if X_train_raw is not None and X_test_raw is not None:
            y_train = self.df.loc[X_train_raw.index, self.target]
            y_test = self.df.loc[X_test_raw.index, self.target]
        else:
            X_full, y_full = self.get_full_data()
            X_train_raw, X_test_raw, y_train, y_test = train_test_split(
                X_full, y_full, test_size=test_size, random_state=42
            )

        X_tr = X_train_raw[self.features]
        X_te = X_test_raw[self.features]

        # Fit transforms on training data only – prevents leakage
        X_train_sc = self.scaler.fit_transform(self.imputer.fit_transform(X_tr))
        X_test_sc = self.scaler.transform(self.imputer.transform(X_te))

        self.y_train = y_train
        self.y_test = y_test

        return X_train_sc, X_test_sc, y_train, y_test


# ---------------------------------------------------------------------------
# Base Model Layer
# ---------------------------------------------------------------------------


@dataclass
class ModelTuner:
    """
    Wraps a single base estimator with hyperparameter search and OOF
    prediction generation.

    Parameters
    ----------
    model : sklearn-compatible estimator
    param_grid : dict
        Grid of hyperparameters passed to ``GridSearchCV``.
    name : str
        Human-readable label (e.g. "RF", "XGB", "SVR").
    """

    model: object
    param_grid: Dict
    name: str
    best_model: object = field(default=None, init=False, repr=False)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def tune(self, X: np.ndarray, y: pd.Series) -> object:
        """
        Fit a 5-fold grid search and store the best estimator.

        Returns
        -------
        best_model : fitted sklearn estimator
        """
        grid = GridSearchCV(
            self.model,
            self.param_grid,
            cv=5,
            scoring="neg_mean_squared_error",
            n_jobs=-1,
        )
        grid.fit(X, y)
        self.best_model = grid.best_estimator_
        print(f"  [{self.name}] Best params: {grid.best_params_}")
        return self.best_model

    def generate_oof(
        self, X_train: np.ndarray, y_train: pd.Series, X_test: np.ndarray
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Produce Out-of-Fold predictions for *X_train* and averaged
        predictions for *X_test* via 5-fold cross-validation.

        Parameters
        ----------
        X_train, y_train : training partition
        X_test : held-out test partition

        Returns
        -------
        oof_preds : np.ndarray, shape (n_train,)
        test_preds : np.ndarray, shape (n_test,)  — mean across folds
        """
        if self.best_model is None:
            raise RuntimeError(f"Call .tune() before .generate_oof() for {self.name}.")

        kf = KFold(n_splits=5, shuffle=True, random_state=42)
        oof_preds = np.zeros(len(y_train))
        fold_test_preds: List[np.ndarray] = []

        for tr_idx, val_idx in kf.split(X_train):
            fold_model = clone(self.best_model)
            fold_model.fit(X_train[tr_idx], y_train.iloc[tr_idx])
            oof_preds[val_idx] = fold_model.predict(X_train[val_idx])
            fold_test_preds.append(fold_model.predict(X_test))

        return oof_preds, np.mean(fold_test_preds, axis=0)


# ---------------------------------------------------------------------------
# Stacking Orchestrator
# ---------------------------------------------------------------------------


class StackingOrchestrator:
    """
    Coordinates the full two-level stacked ensemble pipeline.

    The outer nested cross-validation loop separates hyperparameter search
    from final performance estimation, preventing optimistic bias.

    Parameters
    ----------
    data_handler : BiomassDataHandler
    base_configs : list[ModelTuner]
        One ``ModelTuner`` per base learner.
    meta_model : sklearn estimator
        Level-1 meta-learner (defaults to ``Ridge(alpha=1.0)``).
    """

    def __init__(
        self,
        data_handler: BiomassDataHandler,
        base_configs: List[ModelTuner],
        meta_model: object = None,
    ) -> None:
        self.handler = data_handler
        self.base_configs = base_configs
        self.meta_model = meta_model or Ridge(alpha=1.0)

        # Persistent artefacts populated after the final fold
        self.models: Dict[str, object] = {}
        self.outer_results: List[Dict] = []

        # Stored for post-hoc analysis and Streamlit demo
        self.last_meta_X_train: Optional[pd.DataFrame] = None
        self.last_meta_X_test: Optional[pd.DataFrame] = None
        self.last_y_test: Optional[pd.Series] = None
        self.last_final_preds: Optional[np.ndarray] = None
        self.trained_scaler: Optional[StandardScaler] = None
        self.trained_imputer: Optional[SimpleImputer] = None

    # ------------------------------------------------------------------
    # Training
    # ------------------------------------------------------------------

    def run_nested_stacking(self, n_outer: int = 5) -> pd.DataFrame:
        """
        Execute the nested cross-validation stacking pipeline.

        Each outer fold:
          1. Splits data into outer train / test partitions.
          2. Preprocesses (impute + scale) on the outer train set.
          3. Tunes each base learner via inner grid search.
          4. Generates OOF meta-features for the Ridge meta-model.
          5. Fits the Ridge meta-model and evaluates on the outer test set.

        The trained base models and meta-model from the **final** outer fold
        are stored as production assets for inference.

        Parameters
        ----------
        n_outer : int
            Number of outer cross-validation folds (default 5).

        Returns
        -------
        results_df : pd.DataFrame  — per-fold metrics for all models
        """
        X, y = self.handler.get_full_data()
        outer_cv = KFold(n_splits=n_outer, shuffle=True, random_state=42)

        print(f"\n[StackingOrchestrator] Starting {n_outer}-fold nested CV...\n")

        for fold, (train_idx, test_idx) in enumerate(outer_cv.split(X, y), start=1):
            print(f"── Outer Fold {fold}/{n_outer} ──────────────────────────────")

            # 1. Partition
            X_tr_raw = X.iloc[train_idx]
            X_te_raw = X.iloc[test_idx]
            y_tr = y.iloc[train_idx]
            y_te = y.iloc[test_idx]

            # 2. Preprocess (fit on outer train only)
            X_tr_sc, X_te_sc, y_tr, y_te = self.handler.prepare_split(
                X_tr_raw, X_te_raw
            )

            # 3. Build meta-feature matrices via OOF
            meta_X_train = pd.DataFrame(index=range(len(y_tr)))
            meta_X_test = pd.DataFrame(index=range(len(y_te)))

            for tuner in self.base_configs:
                tuner.tune(X_tr_sc, y_tr)
                oof, test_preds = tuner.generate_oof(X_tr_sc, y_tr, X_te_sc)
                meta_X_train[tuner.name] = oof
                meta_X_test[tuner.name] = test_preds

            # 4. Train meta-model on OOF predictions
            self.meta_model.fit(meta_X_train, y_tr)
            final_preds = self.meta_model.predict(meta_X_test)

            # 5. Log metrics
            self._log_metrics(y_te, final_preds, meta_X_test, fold)

            # Persist artefacts from the final fold for production use
            if fold == n_outer:
                self._persist_fold_artefacts(
                    meta_X_train, meta_X_test, y_te, final_preds
                )

        return pd.DataFrame(self.outer_results)

    # ------------------------------------------------------------------
    # Inference
    # ------------------------------------------------------------------

    def predict(
        self, raw_inputs: Dict[str, float]
    ) -> Tuple[float, Dict[str, float]]:
        """
        Run the full two-stage inference pipeline on a single observation.

        Stage 1 — Apply the same imputer + scaler fitted during training,
                   then generate Level-0 predictions from each base model.
        Stage 2 — Stack the three base predictions into a (1, 3) vector
                   and pass through the Ridge meta-model.

        Parameters
        ----------
        raw_inputs : dict
            Keys must match ``MODEL_FEATURES`` exactly.

        Returns
        -------
        final_pred : float — meta-model output in Mg/ha
        base_preds : dict  — individual base model predictions
        """
        if not self.models:
            raise RuntimeError(
                "No trained models found. Run .run_nested_stacking() first "
                "or load saved artefacts via .load_artefacts()."
            )

        # Build the interaction term
        raw_inputs = dict(raw_inputs)
        raw_inputs["precip_clay_interaction"] = (
            raw_inputs["annual_precip"] * raw_inputs["clay"]
        )

        # Align column order to training order
        df = pd.DataFrame([raw_inputs])[MODEL_FEATURES]

        # Apply saved preprocessing transforms
        X_sc = self.trained_scaler.transform(
            self.trained_imputer.transform(df)
        )

        # Level-0 predictions
        base_preds: Dict[str, float] = {}
        for name in BASE_MODEL_NAMES:
            base_preds[name] = float(self.models[name].predict(X_sc)[0])

        # Level-1 meta prediction
        meta_input = np.array(list(base_preds.values())).reshape(1, -1)
        final_pred = float(self.meta_model.predict(meta_input)[0])

        return final_pred, base_preds

    # ------------------------------------------------------------------
    # Serialisation
    # ------------------------------------------------------------------

    def save_artefacts(
        self, output_dir: str = "saved_models", version: str = "1.0"
    ) -> str:
        """
        Persist all production artefacts to a versioned directory.

        Saves
        -----
        - ``meta_model.joblib``           Ridge meta-learner
        - ``base_model_<name>.joblib``    One file per base learner
        - ``imputer.joblib``              Fitted SimpleImputer
        - ``scaler.joblib``               Fitted StandardScaler
        - ``metadata.json``               Feature order + version info

        Returns
        -------
        output_dir : str — absolute path to the artefact directory
        """
        os.makedirs(output_dir, exist_ok=True)

        joblib.dump(self.meta_model, os.path.join(output_dir, "meta_model.joblib"))
        joblib.dump(self.trained_imputer, os.path.join(output_dir, "imputer.joblib"))
        joblib.dump(self.trained_scaler, os.path.join(output_dir, "scaler.joblib"))

        for name, model in self.models.items():
            joblib.dump(
                model, os.path.join(output_dir, f"base_model_{name}.joblib")
            )

        # Compute mean CV metrics per model for metadata
        cv_metrics: Dict = {}
        if self.outer_results:
            _df = pd.DataFrame(self.outer_results)
            for model_name in _df["model"].unique():
                _rows = _df[_df["model"] == model_name]
                cv_metrics[model_name] = {
                    "r2": round(float(_rows["r2"].mean()), 4),
                    "rmse": round(float(_rows["rmse"].mean()), 4),
                    "mae": round(float(_rows["mae"].mean()), 4),
                }

        metadata = {
            "version": version,
            "created_at": datetime.utcnow().isoformat(),
            "features": MODEL_FEATURES,
            "base_models": BASE_MODEL_NAMES,
            "target": TARGET,
            "ridge_coefficients": dict(
                zip(BASE_MODEL_NAMES, self.meta_model.coef_.tolist())
            ),
            "metrics": cv_metrics,
        }
        with open(os.path.join(output_dir, "metadata.json"), "w") as fh:
            json.dump(metadata, fh, indent=2)

        print(f"[StackingOrchestrator] Artefacts saved to '{output_dir}/'")
        return output_dir

    def load_artefacts(self, model_dir: str = "saved_models") -> None:
        """
        Restore a previously serialised ensemble from *model_dir*.

        Parameters
        ----------
        model_dir : str
            Directory produced by ``.save_artefacts()``.
        """
        self.meta_model = joblib.load(os.path.join(model_dir, "meta_model.joblib"))
        self.trained_imputer = joblib.load(
            os.path.join(model_dir, "imputer.joblib")
        )
        self.trained_scaler = joblib.load(
            os.path.join(model_dir, "scaler.joblib")
        )

        self.models = {}
        for name in BASE_MODEL_NAMES:
            path = os.path.join(model_dir, f"base_model_{name}.joblib")
            self.models[name] = joblib.load(path)

        print(f"[StackingOrchestrator] Artefacts loaded from '{model_dir}/'")

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _persist_fold_artefacts(
        self,
        meta_X_train: pd.DataFrame,
        meta_X_test: pd.DataFrame,
        y_test: pd.Series,
        final_preds: np.ndarray,
    ) -> None:
        """Cache final-fold artefacts and fitted base models."""
        self.last_meta_X_train = meta_X_train
        self.last_meta_X_test = meta_X_test
        self.last_y_test = y_test
        self.last_final_preds = final_preds
        self.trained_scaler = self.handler.scaler
        self.trained_imputer = self.handler.imputer

        for tuner in self.base_configs:
            self.models[tuner.name] = tuner.best_model

    def _calculate_metrics(
        self, y_true: pd.Series, y_pred: np.ndarray
    ) -> Dict[str, float]:
        """Return RMSE, MAE, and R² for a single prediction array."""
        mse = mean_squared_error(y_true, y_pred)
        return {
            "rmse": float(np.sqrt(mse)),
            "mae": float(mean_absolute_error(y_true, y_pred)),
            "r2": float(r2_score(y_true, y_pred)),
        }

    def _log_metrics(
        self,
        y_true: pd.Series,
        y_pred_stacked: np.ndarray,
        meta_X_test: pd.DataFrame,
        fold_num: int,
    ) -> None:
        """Record per-fold metrics for the stacked model and each base learner."""
        stacked_metrics = self._calculate_metrics(y_true, y_pred_stacked)
        self.outer_results.append(
            {"model": "Stacked", "fold": fold_num, **stacked_metrics}
        )

        for col in meta_X_test.columns:
            base_metrics = self._calculate_metrics(y_true, meta_X_test[col].values)
            self.outer_results.append(
                {"model": col, "fold": fold_num, **base_metrics}
            )

        print(
            f"  Stacked → MAE: {stacked_metrics['mae']:.4f}  "
            f"RMSE: {stacked_metrics['rmse']:.4f}  "
            f"R²: {stacked_metrics['r2']:.4f}"
        )


# ---------------------------------------------------------------------------
# Default tuning grids
# ---------------------------------------------------------------------------


def build_default_configs() -> List[ModelTuner]:
    """
    Return a ready-to-use list of ``ModelTuner`` objects with sensible
    hyperparameter grids for the Rimba Raya biomass task.
    """
    return [
        ModelTuner(
            model=RandomForestRegressor(random_state=42),
            param_grid={"n_estimators": [100, 200], "max_depth": [5, 10, None]},
            name="RF",
        ),
        ModelTuner(
            model=XGBRegressor(
                objective="reg:squarederror", random_state=42, verbosity=0
            ),
            param_grid={
                "learning_rate": [0.01, 0.1],
                "max_depth": [3, 5],
                "n_estimators": [100, 200],
            },
            name="XGB",
        ),
        ModelTuner(
            model=SVR(),
            param_grid={"C": [1, 10, 100], "kernel": ["rbf", "linear"]},
            name="SVR",
        ),
    ]


# ---------------------------------------------------------------------------
# Entry point (training run)
# ---------------------------------------------------------------------------


if __name__ == "__main__":
    DATA_PATH = os.path.join(
        os.path.dirname(__file__), "rimba_raya_final.csv"
    )

    handler = BiomassDataHandler(DATA_PATH, MODEL_FEATURES, TARGET)
    handler.load()
    handler.engineer_features()

    configs = build_default_configs()
    orchestrator = StackingOrchestrator(handler, configs)

    results_df = orchestrator.run_nested_stacking(n_outer=5)
    print("\nCross-Validation Summary:")
    print(
        results_df.groupby("model")[["rmse", "mae", "r2"]]
        .mean()
        .round(4)
        .to_string()
    )

    orchestrator.save_artefacts(output_dir="saved_models")
